### ISSUE TITLE
safer_rails_console doesn't work in alerts service rails console mode in sandbox mode

### ISSUE THREAD

**Issue by jturkel** [salsify/safer_rails_console#13]
Here's the output of my session:

```
jturkel:~/salsify/dandelion → feature/independent-client-jobs $ heroku run rails console -a alerts-service-prod
Running rails console on ⬢ alerts-service-prod... up, run.3086 (Standard-1X)
WARNING: YOU ARE USING RAILS CONSOLE IN PRODUCTION!
Changing data can cause serious data loss. Make sure you know what you're doing.
Loading production environment in sandbox (Rails 5.0.5)
Any modifications you make will be rolled back on exit
alerts-service(prod)(sandboxed):001:0> alert1 = Alerts::Alert.unscoped.find('s-bb81c329-571f-449b-84c6-2b995f02ca76')
ArgumentError: wrong number of arguments (given 5, expected 1..4)
  from /app/vendor/bundle/ruby/2.4.0/gems/safer_rails_console-0.1.2/lib/safer_rails_console/patches/sandbox/auto_rollback.rb:8:in `log'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:605:in `exec_cache'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:589:in `execute_and_clear'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/querying.rb:39:in `find_by_sql'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:702:in `exec_queries'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:583:in `load'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:260:in `records'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:527:in `find_take'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:100:in `take'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:477:in `find_one'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:458:in `find_with_ids'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:66:in `find'
  from (irb):1
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/console.rb:65:in `start'
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/console_helper.rb:9:in `start'
  from /app/vendor/bundle/ruby/2.4.0/gems/safer_rails_console-0.1.2/lib/safer_rails_console/patches/railtie/sandbox.rb:16:in `start'
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/commands_tasks.rb:78:in `console'
  from /app/vendor/bundle/ruby/2.4.0/gems/safer_rails_console-0.1.2/lib/safer_rails_console/patches/boot/sandbox_flag.rb:47:in `console'
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands.rb:18:in `<top (required)>'
  from /app/bin/rails:9:in `require'
  from /app/bin/rails:9:in `<main>'
```
The same query works fine when not run in sandbox mode.

**Comment by timothysu** [comment]
Seems like Rails 5+ has a 5th optional `type_casted_binds` argument - will patch this ASAP.

**Comment by ecopoesis** [comment]
I'm having a similar issue with the email-service:

With sandbox on last fails:
```
[miker@starscream.local:~/code/salsify-ruby] (master)$ heroku run rails console --app salsify-email-service-prod
Running rails console on ⬢ salsify-email-service-prod... up, run.7081 (Standard-1X)
WARNING: YOU ARE USING RAILS CONSOLE IN PRODUCTION!
Changing data can cause serious data loss. Make sure you know what you're doing.
Loading production environment in sandbox (Rails 5.0.5)
Any modifications you make will be rolled back on exit
email-service(prod)(sandboxed):001:0> Emails::ProcessedEmail.last
ArgumentError: wrong number of arguments (given 5, expected 1..4)
	from /app/vendor/bundle/ruby/2.4.0/gems/safer_rails_console-0.1.2/lib/safer_rails_console/patches/sandbox/auto_rollback.rb:8:in `log'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:605:in `exec_cache'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:589:in `execute_and_clear'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/querying.rb:39:in `find_by_sql'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:702:in `exec_queries'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:583:in `load'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:260:in `records'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:256:in `to_a'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:563:in `find_nth_with_limit'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:592:in `find_nth_with_limit_and_offset'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:545:in `find_nth'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:122:in `first'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:154:in `last'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/querying.rb:3:in `last'
	from (irb):1
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/console.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/console_helper.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/safer_rails_console-0.1.2/lib/safer_rails_console/patches/railtie/sandbox.rb:16:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /app/vendor/bundle/ruby/2.4.0/gems/safer_rails_console-0.1.2/lib/safer_rails_console/patches/boot/sandbox_flag.rb:47:in `console'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands.rb:18:in `<top (required)>'
	from /app/bin/rails:4:in `require'
	from /app/bin/rails:4:in `<main>'
```

WIth sandbox off it works:
```
[miker@starscream.local:~/code/salsify-ruby] (master)$ heroku run 'bundle exec rails console --no-sandbox' --app salsify-email-service-prod
Running bundle exec rails console --no-sandbox on ⬢ salsify-email-service-prod... up, run.7272 (Standard-1X)
WARNING: YOU ARE USING RAILS CONSOLE IN PRODUCTION!
Changing data can cause serious data loss. Make sure you know what you're doing.
Loading production environment (Rails 5.0.5)
email-service(prod)(unsandboxed):001:0> Emails::ProcessedEmail.last
=> #<Emails::ProcessedEmail id: 33471, request_id: SalsifyUuid(s-55c37118-9d4b-4938-9efe-8ceacf30b51a), recipient_address: "cavery@tgroupusa.com", created_at: "2017-08-15 13:58:50", template_name: "publication-success", organization_id: SalsifyUuid(s-e7e8b58a-ea21-4787-bdc9-f92af4990950), data: {"body"=>"<p>This is notification that the 2018 Nordica Boot GMC Channel has published successfully.</p>", "channel"=>{"id"=>"s-782e2354-3cb8-49fe-8d2a-765dc6380693", "url"=>"https://app.salsify.com/app/orgs/s-e7e8b58a-ea21-4787-bdc9-f92af4990950/channels/49708", "name"=>"Google Manufacturer 2018 Nordica Boots", "external_id"=>49708}, "subject"=>"Successful 2018 Nordica Boot Publication to GMC"}, status: "email_sent", error_message: nil, reply_to: "support@salsify.com">
```

**Comment by timothysu** [comment]
@jturkel @ecopoesis i'll be cutting a release for this tonight
